---
{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "policy.fullname" . }}-config-policy
  labels:
    app: {{ template "policy.name" . }}-config-policy
    chart: {{ template "policy.chart" . }}
    component: "governance"
    release: {{ .Release.Name }}
    controller: "operator"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "policy.name" . }}-config-policy
      component: "governance"
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: {{ template "policy.name" . }}-config-policy
        component: "governance"
        controller: "operator"
        name: config-policy-ctrl
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "policy.chart" . }}
    spec:
      serviceAccountName: {{ template "policy.fullname" . }}
      containers:
      - name: config-policy-controller
        image: "{{ .Values.global.imageOverrides.config_policy_controller }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        command: ["config-policy-controller"]
        args:
          - "--enable-lease=true"
          - "--cluster-name={{ .Values.clusterName }}"
        env:
          - name: WATCH_NAMESPACE
            value: "{{ .Values.clusterNamespace }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "config-policy-ctrl"
          {{- if .Values.global.proxyConfig.HTTP_PROXY }}
          - name: HTTP_PROXY
            value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
          - name: HTTPS_PROXY
            value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.NO_PROXY }}
          - name: NO_PROXY
            value: {{ .Values.global.proxyConfig.NO_PROXY }}
          {{- end }}
        livenessProbe: null
        readinessProbe: null
      volumes:
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.hubKubeConfigSecret }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
