# Copyright Contributors to the Open Cluster Management project

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.imagePullSecret }}
imagePullSecrets:
- name: {{ .Values.imagePullSecret }}
{{- end }}
metadata:
  name: {{ template "controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
