# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "iamPolicyController.fullname" . }}
  labels:
    app: {{ template "iamPolicyController.fullname" . }}
    chart: {{ template "iamPolicyController.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "iamPolicyController.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        k8s-app: {{ template "iamPolicyController.name" . }}
        app: {{ template "iamPolicyController.fullname" . }}
        chart: {{ template "iamPolicyController.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "iamPolicyController.serviceAccount" . }}
      containers:
      - name: {{ template "iamPolicyController.name" . }}
        image: "{{ .Values.global.imageOverrides.iam_policy_controller }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        args:
        - --enable-lease=true
        - --cluster-name={{ .Values.clusterName }}
        - --v={{ .Values.args.verbosity }}
        {{- if .Values.args.frequency }}
        - --update-frequency={{ .Values.args.frequency }}
        {{- end }}
        {{- if semverCompare "< 1.14.0" .Capabilities.KubeVersion.Version }}
        - --legacy-leader-elect=true
        {{- end }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pgrep iam-policy -l
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec echo start iam-policy-controller"]
          initialDelaySeconds: 10
          timeoutSeconds: 2
        env:
        - name: WATCH_NAMESPACE
          value: "{{ .Values.clusterNamespace }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "iamPolicyController.fullname" . }}
        {{- if .Values.global.proxyConfig.HTTP_PROXY }}
        - name: HTTP_PROXY
          value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
        {{- end }}
        {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
        - name: HTTPS_PROXY
          value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
        {{- end }}
        {{- if .Values.global.proxyConfig.NO_PROXY }}
        - name: NO_PROXY
          value: {{ .Values.global.proxyConfig.NO_PROXY }}
        {{- end }}
        resources:
          limits:
            memory: "300Mi"
          requests:
            memory: "150Mi"
        securityContext:
          privileged: {{ .Values.securityContext.privileged }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          capabilities:
              drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- end }}
