# Copyright Contributors to the Open Cluster Management project

org: open-cluster-management
replicas: 1
args:
  frequency: 30
  verbosity: 0
  defaultDuration: null
securityContext:
  pod:
    runAsNonRoot: true
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    privileged: false

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

serviceAccount:
  create: true

clusterName: null
nameOverride: klusterlet-addon-iampolicyctrl
fullnameOverride: klusterlet-addon-iampolicyctrl


global:
  imagePullPolicy: IfNotPresent
  imagePullSecret: null
  imageOverrides:
    cert_policy_controller: quay.io/open-cluster-management/cert-policy-controller:3.6.0
    klusterlet_addon_lease_controller: quay.io/open-cluster-management/klusterlet-addon-lease-controller:2.2.0
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
