---
org: open-cluster-management
replicas: 1

args:
  frequency: 30
  verbosity: 0

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

clusterName: null
clusterNamespace: ""

nameOverride: klusterlet-addon-certpolicyctrl
fullnameOverride: klusterlet-addon-certpolicyctrl

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

global:
  imagePullPolicy: IfNotPresent
  imagePullSecret: null
  imageOverrides:
    iam_policy_controller: quay.io/open-cluster-management/iam-policy-controller:1.0.0
    klusterlet_addon_lease_controller: quay.io/open-cluster-management/klusterlet-addon-lease-controller:2.2.0
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
